set(_CATKIN_CURRENT_PACKAGE "jetson_tools")
set(jetson_tools_VERSION "0.0.0")
set(jetson_tools_MAINTAINER "jetson <jetson@todo.todo>")
set(jetson_tools_PACKAGE_FORMAT "2")
set(jetson_tools_BUILD_DEPENDS "rospy" "sensor_msgs" "std_msgs")
set(jetson_tools_BUILD_EXPORT_DEPENDS "rospy" "sensor_msgs" "std_msgs")
set(jetson_tools_BUILDTOOL_DEPENDS "catkin")
set(jetson_tools_BUILDTOOL_EXPORT_DEPENDS )
set(jetson_tools_EXEC_DEPENDS "rospy" "sensor_msgs" "std_msgs")
set(jetson_tools_RUN_DEPENDS "rospy" "sensor_msgs" "std_msgs")
set(jetson_tools_TEST_DEPENDS )
set(jetson_tools_DOC_DEPENDS )
set(jetson_tools_URL_WEBSITE "")
set(jetson_tools_URL_BUGTRACKER "")
set(jetson_tools_URL_REPOSITORY "")
set(jetson_tools_DEPRECATED "")